config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/formulario', to: 'contact#form', as: :my_form
  get '/destino', to: 'contact#destiny', as: :destiny

  post '/destino', to: 'contact#destiny', as: :post_destiny
  get '/fim', to: 'contact#final', as: :final
  post '/link', to: 'contact#liker', as: :liker
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def form
    end

    def destiny
        
        redirect_to final_path
    end

    def liker
        respond_to do |format|
            format.html { redirect_to final_path }
            format.js { render json: {message: 'oi'}}
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/_myform.html.erb
<h2>Oi Gente, aqui é o <%= name%></h2>
<%= link_to  "text", liker_path, method: :post %>
<%= form_with url: post_destiny_path, class: 'my-form', remote: true do |f|%>
<%= f.select :genero, [["Masculino", 0],["Femino",1]]%>
<%= f.check_box :blue_eye %>
<%= f.text_area :dissertacao%>
<%= f.password_field :password%>
<%= f.email_field :email%>
<%= f.text_field :name%>
<%= f.submit "Clique aqui"%>
<% end %>

app/views/contact/final.html.erb
<h1>Destino Final</h1>

app/views/contact/form.html.erb
<h1>Bem vindo ao meu formulário</h1>
<%= render 'myform', name: "Lucas"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aula2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>